In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
crime = pd.read_csv("/Users/veer.pth/Desktop/Sem 5/Data Science 3/Sprints and Submission/DatScience 3 Main Project/Crime_Data_from_2020_to_Present.csv")

In [3]:
acs = pd.read_csv("/Users/veer.pth/Desktop/Sem 5/Data Science 3/Data Science 2/external/acs_la_tract_2022.csv")

In [4]:
tracts = gpd.read_file("/Users/veer.pth/Desktop/Sem 5/Data Science 3/Data Science 2/external/la_tracts.geojson")

In [5]:
crime.head(), acs.head(), tracts.head()

(       DR_NO               Date Rptd                DATE OCC  TIME OCC  AREA  \
 0  211507896  04/11/2021 12:00:00 AM  11/07/2020 12:00:00 AM       845    15
 1  201516622  10/21/2020 12:00:00 AM  10/18/2020 12:00:00 AM      1845    15
 2  240913563  12/10/2024 12:00:00 AM  10/30/2020 12:00:00 AM      1240     9
 3  210704711  12/24/2020 12:00:00 AM  12/24/2020 12:00:00 AM      1310     7
 4  201418201  10/03/2020 12:00:00 AM  09/29/2020 12:00:00 AM      1830    14

      AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
 0  N Hollywood         1502         2     354
 1  N Hollywood         1521         1     230
 2     Van Nuys          933         2     354
 3     Wilshire          782         1     331
 4      Pacific         1454         1     420

                                          Crm Cd Desc  ... Status  Status Desc  \
 0                                  THEFT OF IDENTITY  ...     IC  Invest Cont
 1     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT  ...     IC  Invest Cont
 2                                  THEFT OF IDENTITY  ...     IC  Invest Cont
 3  THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...  ...     IC  Invest Cont
 4    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)  ...     IC  Invest Cont

   Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
 0    354.0      NaN       NaN      NaN
 1    230.0      NaN       NaN      NaN
 2    354.0      NaN       NaN      NaN
 3    331.0      NaN       NaN      NaN
 4    420.0      NaN       NaN      NaN

                                    LOCATION Cross Street      LAT       LON
 0   7800    BEEMAN                       AV          NaN  34.2124 -118.4092
 1           ATOLL                        AV     N  GAULT  34.1993 -118.4203
 2  14600    SYLVAN                       ST          NaN  34.1847 -118.4509
 3   6000    COMEY                        AV          NaN  34.0339 -118.3747
 4                   4700    LA VILLA MARINA          NaN  33.9813 -118.4350

 [5 rows x 28 columns],
         geoid  total_pop  median_income  state  county   tract  \
 0  6037101110       4014        68972.0      6      37  101110
 1  6037101122       4164       118859.0      6      37  101122
 2  6037101220       3481        65139.0      6      37  101220
 3  6037101221       3756        53348.0      6      37  101221
 4  6037101222       2808        36779.0      6      37  101222

                              name  b01003_001_moe  b19013_001_moe
 0  Los Angeles County, California           473.0         17023.0
 1  Los Angeles County, California           822.0         31445.0
 2  Los Angeles County, California           467.0         12289.0
 3  Los Angeles County, California           687.0         13611.0
 4  Los Angeles County, California           424.0         22089.0  ,
          GEOID  B01003_001E state county   tract  \
 0  06037670413         4852    06    037  670413
 1  06037650101         5532    06    037  650101
 2  06037620303         4934    06    037  620303
 3  06037574000         5178    06    037  574000
 4  06037571400         5018    06    037  571400

                              NAME  B01003_001_moe  \
 0  Los Angeles County, California           540.0
 1  Los Angeles County, California           906.0
 2  Los Angeles County, California           597.0
 3  Los Angeles County, California           461.0
 4  Los Angeles County, California           522.0

                                             geometry
 0  POLYGON ((-118.4037 33.78136, -118.39236 33.78...
 1  POLYGON ((-118.32645 33.8728, -118.31779 33.87...
 2  POLYGON ((-118.41 33.89055, -118.40791 33.8924...
 3  POLYGON ((-118.11344 33.81412, -118.11308 33.8...
 4  POLYGON ((-118.16432 33.84706, -118.16346 33.8...  )

In [6]:
crime.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

In [7]:
tracts.columns

Index(['GEOID', 'B01003_001E', 'state', 'county', 'tract', 'NAME',
       'B01003_001_moe', 'geometry'],
      dtype='object')

In [8]:
acs.columns

Index(['geoid', 'total_pop', 'median_income', 'state', 'county', 'tract',
       'name', 'b01003_001_moe', 'b19013_001_moe'],
      dtype='object')

In [9]:
import geopandas as gpd
from shapely.geometry import Point

In [10]:
crime_gdf = gpd.GeoDataFrame(
    crime,
    geometry=gpd.points_from_xy(crime["LON"], crime["LAT"]),
    crs="EPSG:4326"
)

crime_gdf.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON,geometry
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092,POINT (-118.4092 34.2124)
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203,POINT (-118.4203 34.1993)
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509,POINT (-118.4509 34.1847)
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747,POINT (-118.3747 34.0339)
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350,POINT (-118.435 33.9813)

In [11]:
tracts = tracts.to_crs("EPSG:4326")
tracts.head()

,GEOID,B01003_001E,state,county,tract,NAME,B01003_001_moe,geometry
0,06037670413,4852,06,037,670413,"Los Angeles County, California",540.0,"POLYGON ((-118.4037 33.78136, -118.39236 33.78..."
1,06037650101,5532,06,037,650101,"Los Angeles County, California",906.0,"POLYGON ((-118.32645 33.8728, -118.31779 33.87..."
2,06037620303,4934,06,037,620303,"Los Angeles County, California",597.0,"POLYGON ((-118.41 33.89055, -118.40791 33.8924..."
3,06037574000,5178,06,037,574000,"Los Angeles County, California",461.0,"POLYGON ((-118.11344 33.81412, -118.11308 33.8..."
4,06037571400,5018,06,037,571400,"Los Angeles County, California",522.0,"POLYGON ((-118.16432 33.84706, -118.16346 33.8..."

In [12]:
tracts_for_join = tracts[["GEOID", "geometry"]]

crime_with_tract = gpd.sjoin(
    crime_gdf,
    tracts_for_join,
    how="left",
    predicate="within"
)

crime_with_tract.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON,geometry,index_right,GEOID
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092,POINT (-118.4092 34.2124),1038.0,06037121600
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203,POINT (-118.4203 34.1993),277.0,06037123410
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509,POINT (-118.4509 34.1847),934.0,06037128303
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747,POINT (-118.3747 34.0339),1405.0,06037270200
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350,POINT (-118.435 33.9813),1267.0,06037275312

In [13]:
crime_with_tract["GEOID"].isna().mean()

np.float64(0.002516440445735335)

In [14]:
crime_with_tract[['DR_NO','LAT','LON','GEOID']].head()

       DR_NO      LAT       LON        GEOID
0  211507896  34.2124 -118.4092  06037121600
1  201516622  34.1993 -118.4203  06037123410
2  240913563  34.1847 -118.4509  06037128303
3  210704711  34.0339 -118.3747  06037270200
4  201418201  33.9813 -118.4350  06037275312

In [15]:
# Add prefix to all ACS columns so teammates know they came from ACS
acs = acs.add_prefix("acs_")

# Fix the geoid name back to 'geoid' for merging
acs = acs.rename(columns={"acs_geoid": "geoid"})

In [16]:
acs = acs.rename(columns={
    "acs_b01003_001_moe": "acs_total_pop_moe",
    "acs_b19013_001_moe": "acs_median_income_moe"
})

acs.head()

,geoid,acs_total_pop,acs_median_income,acs_state,acs_county,acs_tract,acs_name,acs_total_pop_moe,acs_median_income_moe
0,6037101110,4014,68972.0,6,37,101110,"Los Angeles County, California",473.0,17023.0
1,6037101122,4164,118859.0,6,37,101122,"Los Angeles County, California",822.0,31445.0
2,6037101220,3481,65139.0,6,37,101220,"Los Angeles County, California",467.0,12289.0
3,6037101221,3756,53348.0,6,37,101221,"Los Angeles County, California",687.0,13611.0
4,6037101222,2808,36779.0,6,37,101222,"Los Angeles County, California",424.0,22089.0

In [30]:
# Make sure both GEOID keys are strings with leading zeros to length 11
crime_with_tract["geoid"] = crime_with_tract["GEOID"].astype(str).str.zfill(11)

# (After you've reloaded/cleaned ACS and set prefix/renames)
acs["geoid"] = acs["geoid"].astype(str).str.zfill(11)

In [31]:
# Standardize geoid columns as strings
crime_with_tract["geoid"] = crime_with_tract["GEOID"].astype(str).str.strip()
acs["geoid"] = acs["geoid"].astype(str).str.strip()

# Merge crime+tract with ACS contextual features
merged = crime_with_tract.merge(
    acs,
    on="geoid",
    how="left"
)

merged.head()
merged.shape

(1004991, 40)

In [32]:
merged_clean = merged.drop(columns=["geometry", "index_right"], errors="ignore")

merged_clean.shape
merged_clean.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON', 'GEOID', 'geoid', 'acs_total_pop', 'acs_median_income',
       'acs_state', 'acs_county', 'acs_tract', 'acs_name', 'acs_total_pop_moe',
       'acs_median_income_moe'],
      dtype='object')

In [33]:
output_path = "/Users/veer.pth/Desktop/Sem 5/Data Science 3/Data Science 2/context_enriched_dataset.csv"

merged_clean.to_csv(output_path, index=False)

In [34]:
df = pd.read_csv("/Users/veer.pth/Desktop/Sem 5/Data Science 3/Data Science 2/context_enriched_dataset.csv")
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,GEOID,geoid,acs_total_pop,acs_median_income,acs_state,acs_county,acs_tract,acs_name,acs_total_pop_moe,acs_median_income_moe
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,6.037122e+09,6.037122e+09,2635.0,100139.0,6.0,37.0,121600.0,"Los Angeles County, California",366.0,26727.0
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,6.037123e+09,6.037123e+09,3503.0,51828.0,6.0,37.0,123410.0,"Los Angeles County, California",577.0,2752.0
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,6.037128e+09,6.037128e+09,3487.0,41328.0,6.0,37.0,128303.0,"Los Angeles County, California",637.0,11892.0
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,6.037270e+09,6.037270e+09,3697.0,79231.0,6.0,37.0,270200.0,"Los Angeles County, California",567.0,32803.0
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,6.037275e+09,6.037275e+09,1991.0,146389.0,6.0,37.0,275312.0,"Los Angeles County, California",202.0,52658.0

In [28]:
df.shape

(1004991, 38)

In [29]:
df[['geoid', 'acs_total_pop', 'acs_median_income']].head(10)

          geoid  acs_total_pop  acs_median_income
0  6.037122e+09            NaN                NaN
1  6.037123e+09            NaN                NaN
2  6.037128e+09            NaN                NaN
3  6.037270e+09            NaN                NaN
4  6.037275e+09            NaN                NaN
5  6.037202e+09            NaN                NaN
6  6.037232e+09            NaN                NaN
7  6.037187e+09            NaN                NaN
8  6.037111e+09            NaN                NaN
9  6.037138e+09            NaN                NaN

In [35]:
df = df.drop(columns=["GEOID"])